export const dataRecipe = [
  {
    id: 'abc1',
    userName: 'user1',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Red Wine and Mint Souffle',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user1@gmail.com',
    time: 5,
    ingredients: [
      'Potato',
      'Banana',
      'Tomato',
      'Rice',
      'Apple',
      'sugar',
      'Orange',
      'Water',
    ],
    tag: [
      '#homefood',
      '#chefathome',
      '#recipeoftheday',
      '#dinner',
      '#homechef',
      '#recipes',
      '#cookingday',
      '#cookingwithlove',
      '#homecooking',
      '#cook',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc2',
    userName: 'user2',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Banana and Mandarin Buns',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user2@gmail.com',
    time: 45,
    ingredients: ['Banana', 'sugar', 'Orange'],
    tag: ['#chefathome', '#recipeoftheday', '#dinner', '#homechef', '#recipes'],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc3',
    userName: 'user3',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Coconut Pound Cake',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user3@gmail.com',
    time: 12,
    ingredients: ['Potato', 'Apple', 'sugar', 'Water'],
    tag: [
      '#homefood',
      '#dinner',
      '#homechef',
      '#recipes',
      '#homecooking',
      '#cook',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc4',
    userName: 'user4',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Cardamom and Cranberry Pastry',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user4@gmail.com',
    time: 20,
    ingredients: ['Potato', 'Banana', 'Tomato', 'Apple', 'sugar', 'Water'],
    tag: [
      '#homefood',
      '#recipeoftheday',
      '#homechef',
      '#cookingday',
      '#homecooking',
      '#cook',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc5',
    userName: 'user5',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Tenderized Salty & Sour Potato Beef',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user5@gmail.com',
    time: 35,
    ingredients: ['Tomato', 'Rice', 'sugar', 'Orange', 'Water'],
    tag: ['#chefathome', '#cookingwithlove', '#homecooking', '#cook'],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc6',
    userName: 'user6',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Sautéed Orange & Mustard Bruschetta',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user6@gmail.com',
    time: 50,
    ingredients: ['Potato', 'Banana', 'sugar', 'Orange', 'Water'],
    tag: [
      '#recipeoftheday',
      '#dinner',
      '#cookingday',
      '#cookingwithlove',
      '#homecooking',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc7',
    userName: 'user7',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Blanched Peppermint Pheasant',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user7@gmail.com',
    time: 5,
    ingredients: ['Potato', 'Banana', 'Tomato', 'Rice', 'Apple'],
    tag: [
      '#homefood',
      '#recipeoftheday',
      '#homechef',
      '#recipes',
      '#cookingwithlove',
      '#cook',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc8',
    userName: 'user8',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Red Wine and Mint Souffle',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user8@gmail.com',
    time: 25,
    ingredients: ['Tomato', 'Rice', 'Apple', 'sugar'],
    tag: [
      '#homefood',
      '#dinner',
      '#cookingday',
      '#cookingwithlove',
      '#homecooking',
      '#cook',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc9',
    userName: 'user9',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Red Wine and Mint Souffle',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user9@gmail.com',
    time: 60,
    ingredients: ['Potato', 'Rice', 'Apple', 'sugar', 'Orange', 'Water'],
    tag: [
      '#homefood',
      '#recipeoftheday',
      '#dinner',
      '#cookingday',
      '#cookingwithlove',
      '#homecooking',
      '#cook',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc10',
    userName: 'user10',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Red Wine and Mint Souffle',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user10@gmail.com',
    time: 5,
    ingredients: ['Potato', 'Banana', 'Tomato', 'Orange', 'Water'],
    tag: ['#cook'],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc11',
    userName: 'user11',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Red Wine and Mint Souffle',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user11@gmail.com',
    time: 5,
    ingredients: ['Potato', 'Tomato', 'Apple', 'Orange'],
    tag: ['#homefood', '#dinner', '#homechef', '#recipes', '#cook'],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
  {
    id: 'abc12',
    userName: 'user12',
    dateCreate: '2h ago',
    image: require('../assets/images/recipeImage1.png'),
    images: [
      require('../assets/images/recipe_image.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
      require('../assets/images/recipe_image1.png'),
      require('../assets/images/recipe_image2.png'),
    ],
    nameRecipe: 'Red Wine and Mint Souffle',
    detail:
      'Apparently we had reached a great height in the atmosphere, for the sky was …',
    like: 32,
    comment: 8,
    userImage: require('../assets/images/user.png'),
    followers: 584,
    address: 'Potato Master',
    phone: '+123456789',
    email: 'user12@gmail.com',
    time: 45,
    ingredients: ['Potato', 'Banana', 'Tomato', 'sugar', 'Orange', 'Water'],
    tag: [
      '#homefood',
      '#chefathome',
      '#recipeoftheday',
      '#dinner',
      '#homechef',
      '#recipes',
      '#cookingday',
      '#cookingwithlove',
      '#homecooking',
      '#cook',
    ],
    howToCook: [
      'Heat a Belgian waffle iron.',
      ' Mix the flour, sugar, and baking powder together in a mixing bowl. Stir in 1 cup eggnog, butter, and the egg until well blended. Add more eggnog if needed to make a pourable batter.',
      'Lightly grease or spray the waffle iron with non-stick cooking spray. Pour some batter onto the preheated waffle iron, …',
    ],
    additional: [
      {name: 'Serving Time', data: 12},
      {
        name: 'Nutrition Facts',
        data: '222 calories,6.2 g fat,7.2 g carbohydrates, 28.6 g protein,68 mg cholesterol,268 mg sodium',
      },
      {name: 'Tags', data: 'Sweet, Coconut, Quick, Easy, Homemade'},
    ],
  },
];
