export const SCREEN_NAME = {
  //Auth
  AUTH_SCREEN: 'AUTH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  //Bottom Tab
  MAIN_BOTTOM_TAB_SCREEN: 'MAIN_BOTTOM_TAB_SCREEN',
  //Screen
  RECIPE_FEED_SCREEN: 'RECIPE_FEED_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  USER_PROFILE_SCREEN: 'USER_PROFILE_SCREEN',
  USER_OTHER_PROFILE_SCREEN: 'USER_OTHER_PROFILE_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN',
  MY_RECIPES_SCREEN: 'MY_RECIPES_SCREEN',
  RECIPE_DETAIL_SCREEN: 'RECIPE_DETAIL_SCREEN',
  ADD_EDIT_RECIPE_SCREEN: 'ADD_EDIT_RECIPE_SCREEN',
};
